'use client';
import { FormEvent, useState } from 'react';
const services=['Compra de chatarra','Limpieza de galpón','Limpieza de fábrica','Retiro industrial','Vaciado de depósito','Otro'];
const materials=['Hierro y acero','Cobre','Aluminio','Bronce','Acero inoxidable','Motores eléctricos','Cable de cobre','Chapa','Lote mixto'];
export default function Home(){
 const [sent,setSent]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setLoading(true);const f=new FormData(e.currentTarget);const files=(f.getAll('photos').filter(x=>x instanceof File&&x.size>0)) as File[];f.delete('photos');const payload=Object.fromEntries(f.entries());payload.consent=f.get('consent')==='on';try{const r=await fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw Error(j.error);if(files.length){const up=new FormData();up.append('leadId',j.id);files.forEach(file=>up.append('photos',file));await fetch('/api/upload',{method:'POST',body:up});}setSent(true);}catch(err){setError(err instanceof Error?err.message:'Error de conexión.')}finally{setLoading(false)}}
 return <main>
 <header className="nav"><a className="brand" href="#top" aria-label="MetalYa inicio"><span className="mark">M</span><span>Metal<span>Ya</span></span></a><nav><a href="#servicios">Servicios</a><a href="#proceso">Cómo funciona</a><a href="#empresas">Empresas</a><a href="#cotizar" className="navCta">Cotizar retiro</a></nav></header>
 <section id="top" className="hero"><div className="heroCopy"><div className="pill">♻ COMPRA · RETIRO · LIMPIEZA</div><h1>Tu chatarra ocupa espacio.<br/><em>Nosotros la convertimos en valor.</em></h1><p>Compramos metales, motores y rezagos. Retiramos material de galpones, fábricas, talleres, depósitos y pymes.</p><div className="actions"><a className="btn primary" href="#cotizar">Cotizar mi lote →</a><a className="btn ghost" href="https://wa.me/541100000000?text=Hola%20MetalYa%2C%20quiero%20cotizar%20un%20lote" target="_blank" rel="noreferrer">WhatsApp</a></div><div className="trust"><b>✓ Evaluación por lote</b><b>✓ Retiros coordinados</b><b>✓ Atención a empresas</b></div></div><div className="heroCard"><div className="cardGlow"/><div className="scrapIcon">⚙</div><h3>¿Tenés un lote?</h3><p>Mandanos fotos, material, cantidad aproximada y ubicación.</p><a href="#cotizar">Quiero tasarlo →</a><div className="mini">Sin compromiso · respuesta comercial</div></div></section>
 <section className="stats"><div><strong>01</strong><span>Evaluamos</span></div><div><strong>02</strong><span>Cotizamos</span></div><div><strong>03</strong><span>Retiramos</span></div><div><strong>04</strong><span>Pesamos y clasificamos</span></div></section>
 <section id="servicios" className="section"><div className="eyebrow">QUÉ HACEMOS</div><h2>Un solo proveedor para <span>ordenar y recuperar valor.</span></h2><div className="grid">{[['♻','Compra de chatarra','Hierro, aluminio, cobre, bronce, acero inoxidable y metales recuperables.'],['▣','Limpieza de galpones','Vaciado de rezagos, estructuras, máquinas y material acumulado.'],['⌂','Limpieza de fábricas y pymes','Despeje de plantas, talleres, depósitos y comercios.'],['↗','Retiros por volumen','Evaluamos desde lotes pequeños hasta operaciones industriales.'],['⚙','Motores y maquinaria','Compramos motores eléctricos, máquinas y equipos fuera de uso.'],['▤','Rezagos industriales','Clasificación y retiro de materiales que ya no forman parte de tu operación.']].map(x=><article className="service" key={x[1]}><div className="serviceIcon">{x[0]}</div><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 <section id="proceso" className="dark"><div className="eyebrow">SIMPLE Y DIRECTO</div><h2>Del descarte al espacio libre.</h2><div className="steps"><div><i>01</i><h3>Subís tu solicitud</h3><p>Material, fotos, cantidad aproximada y ubicación.</p></div><div><i>02</i><h3>Analizamos el lote</h3><p>Estimamos composición, valor recuperable y logística.</p></div><div><i>03</i><h3>Coordinamos el retiro</h3><p>Definimos día, horario y modalidad sin frenar tu actividad.</p></div></div></section>
 <section id="empresas" className="section split"><div><div className="eyebrow">PARA EMPRESAS</div><h2>¿Tenés un galpón que necesitás <span>liberar?</span></h2><p className="lead">MetalYa está pensado para operaciones donde hay volumen, materiales mezclados y poco tiempo para ocuparse del retiro.</p><ul className="checks"><li>Clasificación y retiro de materiales</li><li>Operaciones recurrentes por volumen</li><li>Coordinación con responsables de planta</li><li>Evaluación de lotes completos</li><li>Posibilidad de compensar el servicio con material recuperable, según operación</li></ul><a className="btn primary" href="#cotizar">Solicitar visita →</a></div><div className="quoteBox"><div className="bigNumber">$</div><b>¿No sabés cuánto vale?</b><p>No necesitás clasificar todo antes de consultarnos. Con fotos y una descripción inicial podemos orientarte.</p><a href="#cotizar">Enviar fotos del lote →</a></div></section>
 <section className="materialSection"><div className="eyebrow">MATERIALES</div><h2>Decinos qué tenés. <span>Nosotros hacemos el análisis.</span></h2><div className="chips">{materials.map(m=><span key={m}>{m}</span>)}</div></section>
 <section id="cotizar" className="contact"><div><div className="eyebrow">COTIZACIÓN</div><h2>Contanos qué querés retirar.</h2><p>Completá el formulario. La información queda registrada para que podamos gestionar tu consulta.</p><div className="contactNote"><b>¿Es una empresa?</b><span>Indicá el nombre y ubicación del establecimiento para acelerar la evaluación.</span></div><div className="mapCard"><div><b>Zona de atención</b><span>Buenos Aires y alrededores</span></div><a href="https://www.google.com/maps/search/reciclaje+chatarra+Buenos+Aires" target="_blank" rel="noreferrer">Ver zona en Maps ↗</a></div></div><div className="formCard">{sent?<div className="success"><div>✓</div><h3>Solicitud recibida.</h3><p>Ya registramos tus datos. Te vamos a contactar para avanzar con la evaluación.</p><button onClick={()=>setSent(false)}>Enviar otra consulta</button></div>:<form onSubmit={submit}><div className="two"><label>Nombre*<input name="name" required placeholder="Tu nombre"/></label><label>Empresa<input name="company" placeholder="Empresa / pyme"/></label></div><div className="two"><label>Teléfono / WhatsApp*<input name="phone" required placeholder="11 1234 5678"/></label><label>Email<input name="email" type="email" placeholder="nombre@empresa.com"/></label></div><div className="two"><label>Ubicación<input name="location" placeholder="Localidad / zona"/></label><label>Cantidad aprox. (kg)<input name="estimatedKg" type="number" min="0" placeholder="Ej. 800"/></label></div><label>Necesitás*<select name="service" defaultValue="Compra de chatarra">{services.map(s=><option key={s}>{s}</option>)}</select></label><label>Contanos qué tenés<textarea name="message" rows={4} placeholder="Ej.: motores, chapas, perfiles, cables, maquinaria..."/></label><label>Fotos del lote<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple/><small>Hasta 6 fotos · JPG, PNG o WebP · 5 MB por foto</small></label><label className="consent"><input name="consent" type="checkbox" required/> Acepto que MetalYa almacene estos datos para responder y gestionar mi solicitud.</label>{error&&<p className="error">{error}</p>}<button className="btn primary full" disabled={loading}>{loading?'Enviando...':'Solicitar cotización →'}</button><small>Tratamos tus datos únicamente para gestionar la consulta y prestar el servicio. No cargues información sensible.</small></form>}</div></section>
 <footer><div className="brand"><span className="mark">M</span><span>Metal<span>Ya</span></span></div><p>Compra de chatarra · Retiros · Limpieza industrial</p><div><a href="#cotizar">Contacto</a> · <a href="/privacidad">Privacidad</a> · <a href="/admin">Panel</a></div></footer>
 </main>
}
